spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rent-auth?createDatabaseIfNotExist=true
    password: Welcome+123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update 
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    format-sql: true
logging:
	level:
		org:
			hibernate:
				type: trace
